# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1439279788);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1439279908);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1439279428);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1439279668);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1439279548);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 29);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.search.countryCode", "CN");
user_pref("browser.search.defaultenginename", "Google");
user_pref("browser.search.region", "CN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150702234800");
user_pref("browser.slowStartup.averageTime", 2733);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20150702234800");
user_pref("browser.startup.homepage_override.mstone", "39.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4}");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1439279371406");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1439279373315");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1439365773315");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1436768040415");
user_pref("datareporting.policy.firstRunTime", "1436767978802");
user_pref("datareporting.sessions.current.activeTicks", 124);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 3423);
user_pref("datareporting.sessions.current.main", 639);
user_pref("datareporting.sessions.current.sessionRestored", 3548);
user_pref("datareporting.sessions.current.startTime", "1439279305769");
user_pref("datareporting.sessions.current.totalTime", 1487);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.prunedIndex", 0);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"langpack-zh-CN@firefox.mozilla.org\":{\"version\":\"39.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-zh-CN@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:39.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1439279789);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "39.0");
user_pref("extensions.lastPlatformVersion", "39.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"39.0\",\"st\":1435882457000,\"mt\":1435882444000},\"langpack-zh-CN@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-zh-CN@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"39.0\",\"st\":1435879255000}}}");
user_pref("gecko.buildID", "20150702234800");
user_pref("gecko.mstone", "39.0");
user_pref("idle.lastDailyNotification", 1439279628);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1436768043);
user_pref("media.gmp-gmpopenh264.version", "1.4");
user_pref("media.gmp-manager.buildID", "20150702234800");
user_pref("media.gmp-manager.lastCheck", 1439279372);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1439279628);
user_pref("places.history.expiration.transient_current_max_pages", 90091);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1439279628);
user_pref("toolkit.startup.last_success", 1439279306);
user_pref("toolkit.telemetry.previousBuildID", "20150702234800");
